{{- if .Values.server.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "trino.worker" . }}
spec:
  maxReplicas: {{ max (.Values.server.workers) (.Values.server.autoscaling.maxReplicas) }}
  minReplicas: {{ .Values.server.workers }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "trino.worker" . }}
  metrics:
    {{- if .Values.server.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.server.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.server.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.server.autoscaling.targetMemoryUtilizationPercentage }}
      {{- end }}
{{- end }}
