name: PR Update

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  # read on both needed for changes detection
  pull-requests: read
  contents: read
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  changes:
    # Detect which files have been changed on this PR's full history
    uses: SwanseaUniversityMedical/workflows/.github/workflows/changes-pr.yaml@v4.2.0
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      filters: |
        trino-container:
          - './.github/workflows/on-pr-update.yaml'
          - 'containers/trino/**'
          - 'plugins/**'
        chart:
        - './.github/workflows/on-pr-update.yaml'
        - 'charts/**'

    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}

  trino-container:
    # Build the DARE Trino container and push it as :pr-42 and :pr-42-fe45b3h
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).trino-container == 'true'
    uses: SwanseaUniversityMedical/workflows/.github/workflows/on-pr-update-container.yaml@v4.2.0
    with:
      job-name: trino-container
      container-registry: ${{ vars.HARBOR_REGISTRY }}
      container-registry-user: ${{ vars.HARBOR_USER }}
      container-registry-project: ${{ vars.HARBOR_PROJECT }}
      container-registry-repo: ${{ vars.HARBOR_REPO }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-command: |
        docker build -t $IMAGE -f containers/trino/Dockerfile .
    secrets:
      container-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  chart:
    # Build the chart and push it as :pr-42 and :pr-42-fe45b3h
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).chart == 'true'
    uses: SwanseaUniversityMedical/workflows/.github/workflows/on-pr-update-chart.yaml@v4.2.0
    with:
      job-name: chart
      chart: charts/**
      chart-registry: ${{ vars.HARBOR_REGISTRY }}
      chart-registry-user: ${{ vars.HARBOR_USER }}
      chart-registry-project: ${{ vars.HARBOR_PROJECT }}
      chart-registry-repo: ${{ vars.HARBOR_REPO }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      test-command: |
        helm template $CHART --values charts/trino/values.yaml
    secrets:
      chart-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
