name: Release

on:
  push:
    branches:
      - main

permissions:
  # read needed for changes detection
  # write needed to author a Github release
  contents: write
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  changes:
    # Detect which files have been changed on this PR's full history
    uses: SwanseaUniversityMedical/workflows/.github/workflows/changes-release.yaml@v5.0.1
    with:
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      filters: |
        trino-container:
          - './.github/workflows/on-release.yaml'
          - 'containers/trino/**'
          - 'plugins/**'
        chart:
          - './.github/workflows/on-release.yaml'
          - 'charts/**'

    secrets:
      slack-token: ${{ secrets.SLACK_TOKEN }}

  trino-container:
    # Build the DARE api container and push it as :rc-1.0.0
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).trino-container == 'true'
    uses: SwanseaUniversityMedical/workflows/.github/workflows/build-and-test-release-container.yaml@v5.0.1
    with:
      job-name: trino-container
      registry: ${{ vars.HARBOR_REGISTRY }}
      registry-user: ${{ vars.HARBOR_USER }}
      registry-repo: dare/trino
      release-tag-format: 'DARE-Trino-Container-${version}'
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      build-file: containers/trino/Dockerfile
      build-context: .
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}

  chart:
    # Build the chart and push it as x.y.z-rc
    needs: changes
    if: fromJSON(needs.changes.outputs.changes).chart == 'true'
    uses: SwanseaUniversityMedical/workflows/.github/workflows/on-release-chart.yaml@v5.0.1
    with:
      job-name: chart
      chart-registry: ${{ vars.HARBOR_REGISTRY }}
      chart-registry-user: ${{ vars.HARBOR_USER }}
      chart-registry-project: ${{ vars.HARBOR_PROJECT }}
      chart-registry-repo: ${{ vars.HARBOR_REPO }}
      release-tag-format: 'DARE-Trino-Helm-${version}'
      cosign-public-key: ${{ vars.COSIGN_PUBLIC_KEY }}
      slack-channel: ${{ vars.SLACK_CHANNEL }}
      chart: charts/trino
      test-command: |
        helm template $CHART --values charts/trino/values.yaml
    secrets:
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
      cosign-password: ${{ secrets.COSIGN_PASSWORD }}
      chart-registry-token: ${{ secrets.HARBOR_TOKEN }}
      slack-token: ${{ secrets.SLACK_TOKEN }}
